### ISSUE TITLE
gc_schedule_check_v 表不存在

### ISSUE THREAD

**Issue by dianxiaopao** [giscafer/FinalScheduler#1]
Table 'test.gc_schedule_check_v' doesn't exist
[Err] INSERT INTO `gc_schedule_scheduler` VALUES ('4579', '27', '新人员', '2015-08-12', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4580', '27', '新人员', '2015-08-13', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4581', '27', '新人员', '2015-08-14', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4582', '27', '新人员', '2015-08-15', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4583', '3', '宋涛', '2015-08-09', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4584', '3', '宋涛', '2015-08-10', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4585', '3', '宋涛', '2015-08-11', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4586', '3', '宋涛', '2015-08-12', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4587', '3', '宋涛', '2015-08-13', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4588', '3', '宋涛', '2015-08-14', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4589', '3', '宋涛', '2015-08-15', '', '0');
INSERT INTO `gc_schedule_scheduler` VALUES ('4590', '1', 'giscafer', '2015-08-09', '', '0');
INSERT

**Comment by giscafer** [comment]
@dianxiaopao 确定导入成功没，无错误没？sql应该是包括表和视图的，mysql创建视图按照顺序的，选择出错继续，执行多次
