### ISSUE TITLE
sql文件出错问题

### ISSUE THREAD

**Issue by nnzq** [giscafer/FinalScheduler#11]
Query:
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER  VIEW `gc_schedule_check_statistics_v` AS SELECT * FROM gc_schedule_check_v
UNION 
SELECT * FROM gc_schedule_scheduler_check_v 

Error occured at:2019-01-28 16:17:00
Line no.:2047
Error Code: 1146 - Table 'finalschedule.gc_schedule_check_v' doesn't exist

这一步怎么改都过不去

**Comment by giscafer** [comment]
视图执行顺序调整一下就行了吧。
