### ISSUE TITLE
sql文件有问题

### ISSUE THREAD

**Issue by RodgerLai** [giscafer/FinalScheduler#2]
sql/finalschedule.sql
-- ----------------------------
-- View structure for gc_schedule_check_statistics_v
-- ----------------------------
DROP VIEW IF EXISTS `gc_schedule_check_statistics_v`;
CREATE ALGORITHM=UNDEFINED DEFINER=`dlwy`@`%` **SQL SECURITY DEFINER**  VIEW `gc_schedule_check_statistics_v` AS SELECT * FROM gc_schedule_check_v
UNION 
SELECT * FROM gc_schedule_scheduler_check_v ;

应该去掉粗体部分sql才能正常导入

**Comment by giscafer** [comment]
先给数据库创建`dlwy`用户，再执行语句。sql是用Navicat直接导出的，应该不会有问题
