### ISSUE TITLE
大佬，你写的东西怎么跑起来

### ISSUE THREAD

**Issue by ssw1992** [giscafer/FinalScheduler#5]
怎么跑起来

**Comment by giscafer** [comment]
导入数据库，下载代码，修改对应数据库链接，就差不多了

**Comment by ghost** [comment]
运行到renderTemplate【freemarker渲染，配合前端JS的loadUIAndRender方法接收如下url请求，localhost:8000/FinalScheduler/plan?template】中的configuration.setServletContextForTemplateLoading(request.getServletContext(), "");就报错了，不明原因。如何解决呢？

**Comment by giscafer** [comment]
上传报错原因。@zhlhoney

**Comment by junjun93** [comment]
大佬，请问你写的代码怎么跑起来？我全局搜索localhost、3306等关键词，没有找到数据库配置文件。我得把项目里的账号、密码修改成自己mysql的账号、密码项目才能运行起来啊。你有时间把这些信息写到md文件上，谢谢

**Comment by giscafer** [comment]
@junjun93 Readme 有说明的，数据库需要确认为自己的。https://github.com/giscafer/FinalScheduler#%E4%BD%BF%E7%94%A8
